apiVersion: batch/v1
kind: Job
metadata:
  name: http-server-job
spec:
  template:
    spec:
      containers:
      - name: http-server
        image: ghcr.io/xkasianx/ml-in-production-course:pr-2
      restartPolicy: Never
